services:
  tempo:
    image: grafana/tempo:2.4.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200" # Tempo HTTP
    networks:
      - larity-network

volumes:
  tempo_data:
