version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: larity-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: larity
      POSTGRES_PASSWORD: larity_pass
      POSTGRES_DB: larity

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:

